name: amas_event2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  qr_flutter: ^4.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.0.3
  permission_handler: ^12.0.1
  # image_gallery_saver:
  #   path: packeg/image_gallery_saver
  path_provider: ^2.1.5
  image_editor_plus: ^1.0.4
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1
  screenshot: ^2.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0
  fl_chart: ^1.0.0
  file_picker: ^10.2.0
  rename: ^3.1.0
  audioplayers: ^6.5.0
  connectivity_plus: ^6.1.4
  media_store_plus: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AMASLOGO22025.png"
  background_color: "#000000"
  remove_alpha_ios: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/AMASLOGO22025.png

  fonts:
    # خط Amiri
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
          weight: 700
          style: italic

    # خط Cairo
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900

    # خط Lateef
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef/Lateef-Regular.ttf
        - asset: assets/fonts/Lateef/Lateef-Bold.ttf
          weight: 700

    # خط Scheherazade New
    - family: Scheherazade New
      fonts:
        - asset: assets/fonts/Scheherazade_New/ScheherazadeNew-Regular.ttf
        - asset: assets/fonts/Scheherazade_New/ScheherazadeNew-Bold.ttf
          weight: 700

    # خط El Messiri
    - family: El Messiri
      fonts:
        - asset: assets/fonts/El_Messiri/ElMessiri-Regular.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/El_Messiri/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/El_Messiri/ElMessiri-SemiBold.ttf
          weight: 600

    # خط Harmattan
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan/Harmattan-Regular.ttf
        - asset: assets/fonts/Harmattan/Harmattan-Bold.ttf
          weight: 700

    # خط Changa
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa/Changa-Regular.ttf
        - asset: assets/fonts/Changa/Changa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Changa/Changa-Light.ttf
          weight: 300
        - asset: assets/fonts/Changa/Changa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Changa/Changa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Changa/Changa-ExtraBold.ttf
          weight: 800

    # خط Lalezar
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar/Lalezar-Regular.ttf

    # خط Lemonada
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada/Lemonada-Regular.ttf
        - asset: assets/fonts/Lemonada/Lemonada-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lemonada/Lemonada-Light.ttf
          weight: 300
        - asset: assets/fonts/Lemonada/Lemonada-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lemonada/Lemonada-SemiBold.ttf
          weight: 600

    # خط Almarai
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
